apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: {{ .Values.emailService.service.port }}
      targetPort: {{ .Values.emailService.service.port }}
  type: ClusterIP
