apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: "{{ .Values.emailService.image.repository }}:{{ .Values.emailService.image.tag }}"
          imagePullPolicy: {{ .Values.emailService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.emailService.service.port }}
          env:
            - name: SPRING_MAIL_HOST
              value: smtp.gmail.com
            - name: SPRING_MAIL_PORT
              value: "465"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE
              value: "true"
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: SPRING_MAIL_PASSWORD
