apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: {{ .Values.springApp.service.port }}
      targetPort: {{ .Values.springApp.service.port }}
  type: ClusterIP
