FROM mysql:8.0

# Define variáveis de ambiente padrão (podem ser sobrescritas no compose)
ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_DATABASE=EmpresaVaga

# Copia scripts de inicialização, se quiser
# COPY ./initdb /docker-entrypoint-initdb.d/
